

#         Powered by TabooLib 5.0         #


name: ${name}
main: ${main}
version: ${version}
authors: ['坏黑']

api-version: 1.13

lib-download: true
lib-version: ${libVersion}
loader-version: ${loaderVersion}
